name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: end-2-end
        run: npm run test:e2e
      - name: render deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_DEPLOY_HOOK }}?key=${{ secrets.RENDER_API_KEY }}
