name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: end-2-end
        run: npm run test:e2e
      - name: render deploy
        if: ${{ github.event_name == 'push' }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0

  notification:
    needs: [deployment_pipeline, tag_release]
    if: ${{ always() && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord success
        if: ${{ needs.deployment_pipeline.result == 'success' && needs.tag_release.result == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'AYO PAUSE'
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed successfully.'
      - name: Notify Discord fail
        if: ${{ !(needs.deployment_pipeline.result == 'success' && needs.tag_release.result == 'success') }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'AYO PAUSE'
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed to deploy.'
